"""profile_photo blob to string

Revision ID: 2ade9aec502a
Revises: c2a0e43193fe
Create Date: 2022-04-29 13:31:04.562350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ade9aec502a'
down_revision = 'c2a0e43193fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_mat_file'), 'comments', ['mat_file'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_mat_file'), table_name='comments')
    # ### end Alembic commands ###
