"""time_related_1

Revision ID: 6d1b7668f38c
Revises: 997584ff302d
Create Date: 2022-05-09 16:23:58.571787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d1b7668f38c'
down_revision = '997584ff302d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'time_related')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('time_related', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
