"""profile_photo blob to string

Revision ID: 997584ff302d
Revises: 2ade9aec502a
Create Date: 2022-04-29 13:32:41.312654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997584ff302d'
down_revision = '2ade9aec502a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.String(), nullable=True))
    op.drop_column('users', 'profile_photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo', sa.BLOB(), nullable=True))
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
