"""comments datetime instead integer

Revision ID: c2a0e43193fe
Revises: f691a47ebb16
Create Date: 2022-04-28 15:41:39.104517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a0e43193fe'
down_revision = 'f691a47ebb16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
