"""time_related_2

Revision ID: ca186051f94c
Revises: 6d1b7668f38c
Create Date: 2022-05-09 16:24:26.384286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca186051f94c'
down_revision = '6d1b7668f38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('time_related', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'time_related')
    # ### end Alembic commands ###
