"""comments edited

Revision ID: f691a47ebb16
Revises: 02d31143bdad
Create Date: 2022-04-28 15:26:21.599244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f691a47ebb16'
down_revision = '02d31143bdad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('time_related', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.drop_column('comments', 'unix_time')
    op.drop_column('comments', 'created_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created_date', sa.DATETIME(), nullable=True))
    op.add_column('comments', sa.Column('unix_time', sa.INTEGER(), nullable=False))
    op.drop_column('comments', 'is_private')
    op.drop_column('comments', 'time_related')
    op.drop_column('comments', 'date_created')
    # ### end Alembic commands ###
